#!/bin/bash

thisdir=$(dirname -- "$BASH_SOURCES[0]")
cd "$thisdir" || exit $?

source ./internal-scripts/common.sh

run_setup() {
  # yarn install

  touch external_initiator1.env
  touch external_initiator2.env
  touch external_initiator3.env

  AG_NETWORK_CONFIG="/etc/ag-solo/networks/network-config.json"

  if [ "$1" != "" ]; then
    AG_NETWORK_CONFIG=$1
  fi

  echo "Network config: $AG_NETWORK_CONFIG"

  export AG_NETWORK_CONFIG
  start_docker

  source ./internal-scripts/add-dapp-oracle.sh

  add_dapp_oracle "1" true
  add_dapp_oracle "2"
  add_dapp_oracle "3"

  source ./internal-scripts/add-ei.sh

  add_ei "1"
  add_ei "2"
  add_ei "3"

  source ./internal-scripts/add-bridge.sh

  add_bridge "1"
  add_bridge "2"
  add_bridge "3"

  echo "" > jobids.txt

  source ./internal-scripts/add-jobspec.sh

  add_jobspec "1" "0x7c522c8273973e7bcf4a5dbfcc745dba4a3ab08c1e410167d7b1bdf9cb924f6c"
  add_jobspec "2" "0x06f0d58c43477508c0e5d5901342acf93a0208088816ff303996564a1d8c1c54"
  add_jobspec "3" "0xfaa31acde43e8859565f7576d5a37e6e8ee1b0f6a7c1ae2e8b0ce2bf76248467"

  title "Done setting up Chainlink nodes and services"
#  title "Funding accounts and registering operators..."

#  node ./operatorSetup.js "dry squeeze youth enjoy provide blouse claw engage host what horn next"
#  node ./operatorSetup.js "price trip nominee recycle walk park borrow sausage crucial only wheel joke"
#  node ./operatorSetup.js "camp acid then kid between survey dentist delay actor fox ensure soccer"

  title "All operators are now ready"
  echo "Jobids can be found in jobids.txt or their respective Chainlink GUIs"
}

run_setup "$1"
